channel: stable
addons:
  icantbelieveitsnotvaletudo:
    repository: Poeschl-HomeAssistant-Addons/icantbelieveitsnotvaletudo
    target: icantbelieveitsnotvaletudo
    image: ghcr.io/poeschl-homeassistant-addons/icantbelieveitsnotvaletudo-{arch}
  asterisk:
    repository: Poeschl-HomeAssistant-Addons/asterisk
    target: asterisk
    image: ghcr.io/poeschl-homeassistant-addons/asterisk-{arch}
  container-stats:
    repository: Poeschl-HomeAssistant-Addons/container-stats
    target: container-stats
    image: ghcr.io/poeschl-homeassistant-addons/container-stats-{arch}
  git-exporter:
    repository: Poeschl-HomeAssistant-Addons/git-exporter
    target: git-exporter
    image: ghcr.io/poeschl-homeassistant-addons/git-exporter-{arch}
  marytts:
    repository: Poeschl-HomeAssistant-Addons/marytts
    target: marytts
    image: ghcr.io/poeschl-homeassistant-addons/marytts-{arch}
  juice-shop:
    repository: Poeschl-HomeAssistant-Addons/juice-shop
    target: juice-shop
    image: ghcr.io/poeschl-homeassistant-addons/juice-shop-{arch}
  owasp-zap:
    repository: Poeschl-HomeAssistant-Addons/owasp-zap
    target: owasp-zap
    image: ghcr.io/poeschl-homeassistant-addons/owasp-zap-{arch}
  mitmproxy:
    repository: Poeschl-HomeAssistant-Addons/mitmproxy
    target: mitmproxy
    image: ghcr.io/poeschl-homeassistant-addons/mitmproxy-{arch}
  mopidy:
    repository: Poeschl-HomeAssistant-Addons/mopidy
    target: mopidy
    image: ghcr.io/poeschl-homeassistant-addons/mopidy-{arch}
