channel: stable
addons:
  icantbelieveitsnotvaletudo:
    repository: Poeschl-HomeAssistant-Addons/icantbelieveitsnotvaletudo
    target: icantbelieveitsnotvaletudo
    image: ghcr.io/poeschl-homeassistant-addons/icantbelieveitsnotvaletudo-{arch}
  asterisk:
    repository: Poeschl-HomeAssistant-Addons/asterisk
    target: asterisk
    image: ghcr.io/poeschl-homeassistant-addons/asterisk-{arch}
  container-stats:
    repository: Poeschl-HomeAssistant-Addons/container-stats
    target: container-stats
    image: ghcr.io/poeschl-homeassistant-addons/container-stats-{arch}
  git-exporter:
    repository: Poeschl-HomeAssistant-Addons/git-exporter
    target: git-exporter
    image: ghcr.io/poeschl-homeassistant-addons/git-exporter-{arch}
  marytts:
    repository: Poeschl-HomeAssistant-Addons/marytts
    target: marytts
    image: ghcr.io/poeschl-homeassistant-addons/marytts-{arch}
  juice-shop:
    repository: Poeschl-HomeAssistant-Addons/juice-shop
    target: juice-shop
    image: ghcr.io/poeschl-homeassistant-addons/juice-shop-{arch}
  owasp-zap:
    repository: Poeschl-HomeAssistant-Addons/owasp-zap
    target: owasp-zap
    image: ghcr.io/poeschl-homeassistant-addons/owasp-zap-{arch}
  mitmproxy:
    repository: Poeschl-HomeAssistant-Addons/mitmproxy
    target: mitmproxy
    image: ghcr.io/poeschl-homeassistant-addons/mitmproxy-{arch}
  mopidy:
    repository: Poeschl-HomeAssistant-Addons/mopidy
    target: mopidy
    image: ghcr.io/poeschl-homeassistant-addons/mopidy-{arch}
  mpd:
    repository: Poeschl-HomeAssistant-Addons/mpd
    target: mpd
    image: ghcr.io/poeschl-homeassistant-addons/mpd-{arch}
  picotts:
    repository: Poeschl-HomeAssistant-Addons/picotts
    target: picotts
    image: ghcr.io/poeschl-homeassistant-addons/picotts-{arch}
  pigpio:
    repository: Poeschl-HomeAssistant-Addons/pigpio
    target: pigpio
    image: ghcr.io/poeschl-homeassistant-addons/pigpio-{arch}
  pixelflut:
    repository: Poeschl-HomeAssistant-Addons/pixelflut
    target: pixelflut
    image: ghcr.io/poeschl-homeassistant-addons/pixelflut-{arch}
  rsync:
    repository: Poeschl-HomeAssistant-Addons/rsync
    target: rsync
    image: ghcr.io/poeschl-homeassistant-addons/rsync-{arch}
  rsync-local:
    repository: Poeschl-HomeAssistant-Addons/rsync-local
    target: rsync-local
    image: ghcr.io/poeschl-homeassistant-addons/rsync-local-{arch}
  syncthing:
    repository: Poeschl-HomeAssistant-Addons/syncthing
    target: syncthing
    image: ghcr.io/poeschl-homeassistant-addons/syncthing-{arch}
