name: VNC Viewer
version: 1.6.2
slug: vnc-viewer
panel_icon: mdi:remote-desktop
description: A noVNC client integrated in Home Assistant
url: https://github.com/Poeschl-HomeAssistant-Addons/vnc-viewer
ingress: true
ingress_port: 6080
ingress_entry: vnc.html?autoconnect=true
arch:
- armv7
- armhf
- aarch64
- amd64
- i386
boot: manual
hassio_api: true
init: false
options:
  vnc_server_host: localhost
schema:
  vnc_server_host: str
  vnc_server_port: int?
  vnc_server_password: str?
image: ghcr.io/poeschl-homeassistant-addons/vnc-viewer-{arch}
