name: Syncthing
version: 2.0.2
slug: syncthing
description: Syncthing is a continuous file synchronization program in a de-centralized
  way
url: https://github.com/Poeschl-HomeAssistant-Addons/syncthing
arch:
- aarch64
- amd64
homeassistant: 0.115.0
image: ghcr.io/poeschl-homeassistant-addons/syncthing-{arch}
init: false
schema:
  state_dir: str?
ports:
  8384/tcp: null
  22000/tcp: 22000
  21027/udp: 21027
ingress: true
ingress_port: 8384
panel_title: Syncthing
panel_icon: mdi:sync
map:
- addon_config:rw
- addons:rw
- all_addon_configs:rw
- backup:rw
- homeassistant_config:rw
- media:rw
- share:rw
- ssl:rw
