name: Label Commenter

on:
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: ↩️ Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: ✏️ Comment
        uses: peaceiris/actions-label-commenter@v1.10.0
        with:
          config_file: .github/label-comments.yaml