name: Update edge repository

# yamllint disable-line rule:truthy
on:
  repository_dispatch:
    types: ["update"]

permissions: read-all

jobs:
  workflows:
    uses: Poeschl-HomeAssistant-Addons/workflows/.github/workflows/repository-update.yaml@main
    permissions:
      contents: write
    secrets:
      updater_token: ${{ secrets.UPDATER_TOKEN }}
    with:
      addon: ${{ github.event.client_payload.addon }}
